#!/usr/bin/env python
import asyncio
from ircnotifier.redis2irc import Redis2Irc

conf = {}
bot = Redis2Irc(
    conf=conf,
    nick=conf.get('IRC_NICK', 'ircnotifier'),
    host=conf.get('IRC_SERVER', 'chat.freenode.net'),
    port=7000,
    ssl=True,
    password=conf.get('IRC_PASSWORD'),
    realname='ircnotifier',
    userinfo='IRCNotifier v1, https://github.com/yuvipanda/ircnotifier',
    includes=[
        'irc3.plugins.core',
        'irc3.plugins.ctcp',
        'irc3.plugins.autojoins',
        __name__,  # this register MyPlugin
    ],
    verbose=True,
    ctcp={
        'version': 'ircnotifier %s running on irc3. See {url} for more details.',
        'userinfo': '{userinfo}',
        'ping': 'PONG',
        }
)
asyncio.Task(bot.start())
bot.run()
